version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            npm install
      - add_ssh_keys:
          fingerprints:
            - "91:3f:bc:c7:42:7f:55:72:75:c4:9a:82:9f:ab:26:e9"
      - run:
          name: "Build & Deploy"
          command: /bin/bash ./deploy.sh

workflows:
  build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main
